apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdc-consumer-test-fdstore-reservation
  namespace: enhanced-consumers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdc-consumer-test-fdstore-reservation
  template:
    metadata:
      labels:
        app: cdc-consumer-test-fdstore-reservation
    spec:
      containers:
        - name: cdc-consumer
          image: sekharmuni/enhanced-consumer:latest
          ports:
            - containerPort: 9095
          envFrom:
            - configMapRef:
                name: cdc-consumer-config
            - secretRef:
                name: cdc-consumer-secrets-test-reservation
          env:
            - name: KAFKA_GROUP_ID
              value: "enhanced-consumer-test"
            - name: CDC_TOPICS
              value: "enhanced.fdstore_prda.reservation"
            - name: CDC_TOPIC_TABLE_MAPPINGS
              value: "{'enhanced.fdstore_prda.reservation': 'RESERVATION'}"
            - name: CDC_TABLE_PRIMARY_KEYS
              value: "{'RESERVATION': 'id'}"
            - name: SPRING_KAFKA_CONSUMER_MAX_POLL_RECORDS
              value: "800"
            - name: ORACLE_SCHEMA
              value: "FDSTORE_PRDA"
            - name: POSTGRES_SCHEMA
              value: "fdstore_prda"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9095
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9095
            initialDelaySeconds: 60
            periodSeconds: 15