apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdc-consumer-transp-composite-pk
  namespace: cdc-consumers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdc-consumer-transp-composite-pk
  template:
    metadata:
      labels:
        app: cdc-consumer-transp-composite-pk
        schema: transp
        group: composite-pk
    spec:
      containers:
        - name: cdc-consumer
          image: sekharmuni/cdc-consumer:version1
          ports:
            - containerPort: 9095
          envFrom:
            - configMapRef:
                name: cdc-consumer-config
            - secretRef:
                name: cdc-consumer-secrets
          env:
            - name: KAFKA_GROUP_ID
              value: "transp-composite-pk-group"
            - name: CDC_TOPICS
              value: "devtest.transp.handoff_batchdepotschedule,devtest.transp.handoff_batchroute_breaks,devtest.transp.handoff_batchdispatchex"
            - name: CDC_TOPIC_TABLE_MAPPINGS
              value: "{
                  'devtest.transp.handoff_batchdepotschedule': 'HANDOFF_BATCHDEPOTSCHEDULE',
                  'devtest.transp.handoff_batchroute_breaks': 'HANDOFF_BATCHROUTE_BREAKS',
                  'devtest.transp.handoff_batchdispatchex': 'HANDOFF_BATCHDISPATCHEX'
                }"
            - name: CDC_TABLE_PRIMARY_KEYS
              value: "{
                  'HANDOFF_BATCHDEPOTSCHEDULE': 'batch_id,area,depotarrivaltime,truckdeparturetime,origin_id',
                  'HANDOFF_BATCHROUTE_BREAKS': 'break_id,batch_id,session_name,route_no',
                  'HANDOFF_BATCHDISPATCHEX': 'batch_id,dispatchtime'
                }"
            - name: SPRING_KAFKA_CONSUMER_MAX_POLL_RECORDS
              value: "1000"
            - name: ORACLE_SCHEMA
              value: "TRANSP"
            - name: ORACLE_USER
              value: "transp"
            - name: ORACLE_PASSWORD
              value: "transp"
            - name: POSTGRES_SCHEMA
              value: "transp"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9095
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9095
            initialDelaySeconds: 60
            periodSeconds: 15