apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdc-consumer-transp-medium-low
  namespace: cdc-consumers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdc-consumer-transp-medium-low
  template:
    metadata:
      labels:
        app: cdc-consumer-transp-medium-low
        schema: transp
        group: medium-low
    spec:
      containers:
        - name: cdc-consumer
          image: gcr.io/fd-pr-transapp-dev-use4-01/cdc_consumer:latest
          ports:
            - containerPort: 9095
          envFrom:
            - configMapRef:
                name: cdc-consumer-config
            - secretRef:
                name: cdc-consumer-secrets
          env:
            - name: KAFKA_GROUP_ID
              value: "transp-medium-low-group"
            - name: CDC_TOPICS
              value: "pt.fdstore_prda.deliveryconfirm,pt.fdstore_prda.handoff_batchstop,pt.fdstore_prda.fdx_trip_order,pt.fdstore_prda.fdx_trip,pt.fdstore_prda.fdx_staff,pt.fdstore_prda.fdx_trip_staff,pt.fdstore_prda.handoff_batchroute,pt.fdstore_prda.handoff_batchdispatchex,pt.fdstore_prda.handoff_batchaction,pt.fdstore_prda.handoff_batchtrailer,pt.fdstore_prda.handoff_batchsession,pt.fdstore_prda.handoff_batch,pt.fdstore_prda.handoff_batchdepotschedule,pt.fdstore_prda.handoff_batchroute_breaks,pt.fdstore_prda.dispatch,pt.fdstore_prda.dispatch_resource,pt.fdstore_prda.tip_distribution_batch"
            - name: CDC_TOPIC_TABLE_MAPPINGS
              value: |
                {
                  'pt.fdstore_prda.deliveryconfirm': 'DELIVERYCONFIRM',
                  'pt.fdstore_prda.handoff_batchstop': 'HANDOFF_BATCHSTOP',
                  'pt.fdstore_prda.fdx_trip_order': 'FDX_TRIP_ORDER',
                  'pt.fdstore_prda.fdx_trip': 'FDX_TRIP',
                  'pt.fdstore_prda.fdx_staff': 'FDX_STAFF',
                  'pt.fdstore_prda.fdx_trip_staff': 'FDX_TRIP_STAFF',
                  'pt.fdstore_prda.handoff_batchroute': 'HANDOFF_BATCHROUTE',
                  'pt.fdstore_prda.handoff_batchdispatchex': 'HANDOFF_BATCHDISPATCHEX',
                  'pt.fdstore_prda.handoff_batchaction': 'HANDOFF_BATCHACTION',
                  'pt.fdstore_prda.handoff_batchtrailer': 'HANDOFF_BATCHTRAILER',
                  'pt.fdstore_prda.handoff_batchsession': 'HANDOFF_BATCHSESSION',
                  'pt.fdstore_prda.handoff_batch': 'HANDOFF_BATCH',
                  'pt.fdstore_prda.handoff_batchdepotschedule': 'HANDOFF_BATCHDEPOTSCHEDULE',
                  'pt.fdstore_prda.handoff_batchroute_breaks': 'HANDOFF_BATCHROUTE_BREAKS',
                  'pt.fdstore_prda.dispatch': 'DISPATCH',
                  'pt.fdstore_prda.dispatch_resource': 'DISPATCH_RESOURCE',
                  'pt.fdstore_prda.tip_distribution_batch': 'TIP_DISTRIBUTION_BATCH'
                }
            - name: CDC_TABLE_PRIMARY_KEYS
              value: |
                {
                  'HANDOFF_BATCHSTOP': 'batch_id,weborder_id',
                  'FDX_TRIP_ORDER': 'trip_id,order_id',
                  'FDX_TRIP': 'trip_id',
                  'FDX_STAFF': 'id',
                  'FDX_TRIP_STAFF': 'trip_id,staff_id',
                  'HANDOFF_BATCHROUTE': 'batch_id,session_name,route_no',
                  'HANDOFF_BATCHDISPATCHEX': 'batch_id,dispatchtime',
                  'HANDOFF_BATCHACTION': 'batch_id,action_datetime',
                  'HANDOFF_BATCHTRAILER': 'batch_id,trailer_no',
                  'HANDOFF_BATCHSESSION': 'batch_id,session_name',
                  'HANDOFF_BATCH': 'batch_id',
                  'HANDOFF_BATCHDEPOTSCHEDULE': 'batch_id,area,depotarrivaltime,truckdeparturetime,origin_id',
                  'HANDOFF_BATCHROUTE_BREAKS': 'break_id,batch_id,session_name,route_no',
                  'DISPATCH': 'dispatch_id',
                  'DISPATCH_RESOURCE': 'dispatch_id,resource_id',
                  'TIP_DISTRIBUTION_BATCH': 'batch_id,week_of,delivery_date'
                }
            - name: CDC_ALLOW_DUPLICATES
              value: "DELIVERYCONFIRM"
            - name: POSTGRES_UDT_TABLES
              value: "HANDOFF_BATCHROUTE:BATCH_ID"
            - name: POSTGRES_UDT_TYPE_MAPPING
              value: "{'handoff_routing_route_no':'HANDOFF_ROUTING_ROUTE_NO', 'handoff_roadnet_route_no':'HANDOFF_ROADNET_ROUTE_NO'}"
            - name: POSTGRES_UDT_COLUMN_MAPPING
              value: "{'HANDOFF_BATCHROUTE.ROUTING_ROUTE_NO':'handoff_routing_route_no', 'HANDOFF_BATCHROUTE.ROADNET_ROUTE_NO':'handoff_roadnet_route_no'}"
            - name: SPRING_KAFKA_CONSUMER_MAX_POLL_RECORDS
              value: "1000"
            - name: ORACLE_SCHEMA
              value: "FDSTORE_PRDA"
            - name: POSTGRES_SCHEMA
              value: "fdstore_prda"
          resources:
            requests:
              memory: "2Gi"
              cpu: "2000m"
            limits:
              memory: "4Gi"
              cpu: "4000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9095
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9095
            initialDelaySeconds: 60
            periodSeconds: 15