apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdc-consumer-transp-high-orders
  namespace: cdc-consumers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdc-consumer-transp-high-orders
  template:
    metadata:
      labels:
        app: cdc-consumer-transp-high-orders
        schema: transp
        group: high-orders
    spec:
      containers:
        - name: cdc-consumer
          image: gcr.io/YOUR_PROJECT_ID/cdc-datareplication-app:v1.0.0
          ports:
            - containerPort: 9095
          envFrom:
            - configMapRef:
                name: cdc-consumer-config
            - secretRef:
                name: cdc-consumer-secrets
          env:
            - name: KAFKA_GROUP_ID
              value: "transp-high-orders-group"
            - name: CDC_TOPICS
              value: "mytestp.transp.fdx_orderaction"
            - name: CDC_TOPIC_TABLE_MAPPINGS
              value: "{'mytestp.transp.fdx_orderaction': 'FDX_ORDERACTION'}"
            - name: CDC_TABLE_PRIMARY_KEYS
              value: "{'FDX_ORDERACTION': 'order_action_id'}"
            - name: SPRING_KAFKA_CONSUMER_MAX_POLL_RECORDS
              value: "2000"
            - name: SPRING_KAFKA_CONSUMER_FETCH_MIN_BYTES
              value: "100000"
            - name: ORACLE_SCHEMA
              value: "DLV"
            - name: POSTGRES_SCHEMA
              value: "dlv"
          resources:
            requests:
              memory: "4Gi"
              cpu: "2000m"
            limits:
              memory: "8Gi"
              cpu: "4000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9095
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9095
            initialDelaySeconds: 60
            periodSeconds: 15