apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdc-consumer-dlv-reservation
  namespace: cdc-consumers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdc-consumer-dlv-reservation
  template:
    metadata:
      labels:
        app: cdc-consumer-dlv-reservation
    spec:
      containers:
        - name: cdc-consumer
          image: sekharmuni/cdc-consumer:latest
          ports:
            - containerPort: 9095
          envFrom:
            - configMapRef:
                name: cdc-consumer-config
            - secretRef:
                name: cdc-consumer-secrets
          env:
            - name: KAFKA_GROUP_ID
              value: "dlv-reservation"
            - name: CDC_TOPICS
              value: "devtest.dlv.reservation"
            - name: CDC_TOPIC_TABLE_MAPPINGS
              value: "{'devtest.dlv.reservation': 'RESERVATION'}"
            - name: CDC_TABLE_PRIMARY_KEYS
              value: "{'RESERVATION': 'id'}"
            - name: SPRING_KAFKA_CONSUMER_MAX_POLL_RECORDS
              value: "800"
            - name: ORACLE_SCHEMA
              value: "DLV"
            - name: POSTGRES_SCHEMA
              value: "dlv"
          resources:
            requests:
              memory: "2Gi"
              cpu: "2000m"
            limits:
              memory: "3Gi"
              cpu: "4000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9095
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9095
            initialDelaySeconds: 60
            periodSeconds: 15