apiVersion: v1
kind: Secret
metadata:
  name: cdc-consumer-secrets
  namespace: cdc-consumers
type: Opaque
data:
  # Database Credentials (Base64 encoded)
  POSTGRES_URL: amRiYzpwb3N0Z3Jlc3FsOi8vMTAuNTIuMy42OjU0MzIvcHNxbGRldg==
  POSTGRES_USER: cHNxbGRldg==
  POSTGRES_PASSWORD: V2UxYzBtZTEyMw==