apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdc-consumer-mis
  namespace: cdc-consumers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdc-consumer-mis
  template:
    metadata:
      labels:
        app: cdc-consumer-mis
        schema: mis
        group: mis
    spec:
      containers:
        - name: cdc-consumer
          image: sekharmuni/cdc-consumer:version1
          ports:
            - containerPort: 9095
          envFrom:
            - configMapRef:
                name: cdc-consumer-config
            - secretRef:
                name: cdc-consumer-secrets
          env:
            - name: KAFKA_GROUP_ID
              value: "mis-delivery-event"
            - name: CDC_TOPICS
              value: "devtest.mis.delivery_event"
            - name: CDC_TOPIC_TABLE_MAPPINGS
              value: "{'devtest.mis.delivery_event': 'DELIVERY_EVENT'}"
            - name: CDC_TABLE_PRIMARY_KEYS
              value: "{'DELIVERY_EVENT': 'erporder_id,event,event_timestamp'}"
            - name: SPRING_KAFKA_CONSUMER_MAX_POLL_RECORDS
              value: "2000"
            - name: SPRING_KAFKA_CONSUMER_FETCH_MIN_BYTES
              value: "100000"
            - name: ORACLE_SCHEMA
              value: "MIS"
            - name: ORACLE_USER
              value: "mis"
            - name: ORACLE_PASSWORD
              value: "mis"
            - name: POSTGRES_SCHEMA
              value: "mis"
          resources:
            requests:
              memory: "1Gi"
              cpu: "2000m"
            limits:
              memory: "2Gi"
              cpu: "4000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9095
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9095
            initialDelaySeconds: 60
            periodSeconds: 15