apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdc-consumer-transp-medium-low
  namespace: cdc-consumers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdc-consumer-transp-medium-low
  template:
    metadata:
      labels:
        app: cdc-consumer-transp-medium-low
        schema: transp
        group: medium-low
    spec:
      containers:
        - name: cdc-consumer
          image: gcr.io/fd-pr-transapp-dev-use4-01/cdc_consumer:latest
          ports:
            - containerPort: 9095
          envFrom:
            - configMapRef:
                name: cdc-consumer-config
            - secretRef:
                name: cdc-consumer-secrets
          env:
            - name: KAFKA_GROUP_ID
              value: "transp-medium-low-group"
            - name: CDC_TOPICS
              value: "mytestp.transp.deliveryconfirm,mytestp.transp.handoff_batchstop,mytestp.transp.fdx_order,mytestp.transp.fdx_trip_order,mytestp.transp.fdx_trip,mytestp.transp.fdx_staff,mytestp.transp.fdx_trip_staff,mytestp.transp.handoff_batchroute,mytestp.transp.handoff_batchdispatchex,mytestp.transp.handoff_batchaction,mytestp.transp.handoff_batchtrailer,mytestp.transp.handoff_batchsession,mytestp.transp.handoff_batch,mytestp.transp.handoff_batchdepotschedule,mytestp.transp.handoff_batchroute_breaks,mytestp.transp.dispatch,mytestp.transp.dispatch_resource,mytestp.transp.tip_distribution_batch"
            - name: CDC_TOPIC_TABLE_MAPPINGS
              value: |
                {
                  'mytestp.transp.deliveryconfirm': 'DELIVERYCONFIRM',
                  'mytestp.transp.handoff_batchstop': 'HANDOFF_BATCHSTOP',
                  'mytestp.transp.fdx_order': 'FDX_ORDER',
                  'mytestp.transp.fdx_trip_order': 'FDX_TRIP_ORDER',
                  'mytestp.transp.fdx_trip': 'FDX_TRIP',
                  'mytestp.transp.fdx_staff': 'FDX_STAFF',
                  'mytestp.transp.fdx_trip_staff': 'FDX_TRIP_STAFF',
                  'mytestp.transp.handoff_batchroute': 'HANDOFF_BATCHROUTE',
                  'mytestp.transp.handoff_batchdispatchex': 'HANDOFF_BATCHDISPATCHEX',
                  'mytestp.transp.handoff_batchaction': 'HANDOFF_BATCHACTION',
                  'mytestp.transp.handoff_batchtrailer': 'HANDOFF_BATCHTRAILER',
                  'mytestp.transp.handoff_batchsession': 'HANDOFF_BATCHSESSION',
                  'mytestp.transp.handoff_batch': 'HANDOFF_BATCH',
                  'mytestp.transp.handoff_batchdepotschedule': 'HANDOFF_BATCHDEPOTSCHEDULE',
                  'mytestp.transp.handoff_batchroute_breaks': 'HANDOFF_BATCHROUTE_BREAKS',
                  'mytestp.transp.dispatch': 'DISPATCH',
                  'mytestp.transp.dispatch_resource': 'DISPATCH_RESOURCE',
                  'mytestp.transp.tip_distribution_batch': 'TIP_DISTRIBUTION_BATCH'
                }
            - name: CDC_TABLE_PRIMARY_KEYS
              value: |
                {
                  'DELIVERYCONFIRM': 'confirm_id',
                  'HANDOFF_BATCHSTOP': 'stop_id',
                  'FDX_ORDER': 'order_id',
                  'FDX_TRIP_ORDER': 'trip_order_id',
                  'FDX_TRIP': 'trip_id',
                  'FDX_STAFF': 'staff_id',
                  'FDX_TRIP_STAFF': 'trip_staff_id',
                  'HANDOFF_BATCHROUTE': 'batch_id',
                  'HANDOFF_BATCHDISPATCHEX': 'dispatch_id',
                  'HANDOFF_BATCHACTION': 'action_id',
                  'HANDOFF_BATCHTRAILER': 'trailer_id',
                  'HANDOFF_BATCHSESSION': 'session_id',
                  'HANDOFF_BATCH': 'batch_id',
                  'HANDOFF_BATCHDEPOTSCHEDULE': 'schedule_id',
                  'HANDOFF_BATCHROUTE_BREAKS': 'break_id',
                  'DISPATCH': 'dispatch_id',
                  'DISPATCH_RESOURCE': 'resource_id',
                  'TIP_DISTRIBUTION_BATCH': 'batch_id'
                }
            - name: CDC_ALLOW_DUPLICATES
              value: "DELIVERYCONFIRM"
            - name: POSTGRES_UDT_TABLES
              value: "HANDOFF_BATCHROUTE:BATCH_ID"
            - name: POSTGRES_UDT_TYPE_MAPPING
              value: "{'handoff_routing_route_no':'HANDOFF_ROUTING_ROUTE_NO', 'handoff_roadnet_route_no':'HANDOFF_ROADNET_ROUTE_NO'}"
            - name: POSTGRES_UDT_COLUMN_MAPPING
              value: "{'HANDOFF_BATCHROUTE.ROUTING_ROUTE_NO':'handoff_routing_route_no', 'HANDOFF_BATCHROUTE.ROADNET_ROUTE_NO':'handoff_roadnet_route_no'}"
            - name: SPRING_KAFKA_CONSUMER_MAX_POLL_RECORDS
              value: "1000"
          resources:
            requests:
              memory: "3Gi"
              cpu: "1500m"
            limits:
              memory: "6Gi"
              cpu: "3000m"