apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connector
  namespace: debezium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connector
  template:
    metadata:
      labels:
        app: debezium-connector
    spec:
      containers:
        - name: debezium-connect
          image: quay.io/debezium/connect:latest
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: debezium-config
            - secretRef:
                name: debezium-secrets
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /connectors
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10