apiVersion: v1
kind: ConfigMap
metadata:
  name: debezium-config
  namespace: debezium
data:
  BOOTSTRAP_SERVERS: "bootstrap.transapp-rollback-poc.us-east4.managedkafka.pr-transapp-dev-use4-01.cloud.goog:9092"
  GROUP_ID: "1"
  CONFIG_STORAGE_TOPIC: "connect_configs"
  OFFSET_STORAGE_TOPIC: "connect_offsets"
  STATUS_STORAGE_TOPIC: "connect_statuses"
  CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
  CONNECT_SECURITY_PROTOCOL: "SASL_SSL"
  CONNECT_SASL_MECHANISM: "PLAIN"
  CONNECT_PRODUCER_BOOTSTRAP_SERVERS: "bootstrap.transapp-rollback-poc.us-east4.managedkafka.pr-transapp-dev-use4-01.cloud.goog:9092"
  CONNECT_PRODUCER_SECURITY_PROTOCOL: "SASL_SSL"
  CONNECT_PRODUCER_SASL_MECHANISM: "PLAIN"
  CONNECT_CONSUMER_BOOTSTRAP_SERVERS: "bootstrap.transapp-rollback-poc.us-east4.managedkafka.pr-transapp-dev-use4-01.cloud.goog:9092"
  CONNECT_CONSUMER_SECURITY_PROTOCOL: "SASL_SSL"
  CONNECT_CONSUMER_SASL_MECHANISM: "PLAIN"