apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connector
  namespace: debezium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connector
  template:
    metadata:
      labels:
        app: debezium-connector
    spec:
      containers:
        - name: debezium-connect
          image: quay.io/debezium/connect:latest
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: debezium-config
          env:
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: debezium-secrets
                  key: KAFKA_PASSWORD
            - name: CONNECT_SASL_JAAS_CONFIG
              value: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="$(KAFKA_USERNAME)" password="$(KAFKA_PASSWORD)";'
            - name: CONNECT_PRODUCER_SASL_JAAS_CONFIG
              value: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="$(KAFKA_USERNAME)" password="$(KAFKA_PASSWORD)";'
            - name: CONNECT_CONSUMER_SASL_JAAS_CONFIG
              value: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="$(KAFKA_USERNAME)" password="$(KAFKA_PASSWORD)";'
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /connectors
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10